a=input('Enter the value :- ');
b=input('Enter the value := ');
print(a+b);
c=int(input('Enter the Value'));
d=int(input('Enter The Value2:-'));
print(c+d);
e=float(input('Enter the Value'));
f=float(input('Enter the Value'));
print(e+f);
x=eval(input('Enter the Value'));
y=eval(input('Enter the Value'));
print(x+y);
